version: '3.3'
services:

  backend:
    image: andrewnemo/foodgram_backend:latest
    expose:
      - 8000
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/

  frontend:
    image: andrewnemo/foodgram_backend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
